"use client";

import {Camera,ChevronRight,Images,LoaderCircle,MapPin,MessageCircle,Mic,Paperclip,Pencil,Plus,Settings,Sparkles,Square,X} from "lucide-react";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ensureAnonymousSession,warmAnonymousSession} from "@/lib/supabase-browser";
import {warmKipuLocation} from "@/lib/kipu-client-location";
import {KipuLogo} from "@/components/kipu-logo";
import {saveCameraCapture} from "@/lib/camera-capture-store";

const actions=[
  {label:"Text",hint:"Gedanke oder Idee notieren",icon:Pencil,href:"/write",tone:"bg-[#fff7e8] text-[#d99a39]"},
  {label:"Sprache",hint:"Einfach erzählen",icon:Mic,href:"/voice",tone:"bg-[#eeecff] text-[#6f78f6]"},
  {label:"Foto",hint:"Kamera oder Fotobibliothek",icon:Camera,href:"/camera",tone:"bg-[#e8f3ee] text-[#5d9b84]"},
  {label:"Datei",hint:"Dokument oder Bild hinzufügen",icon:Paperclip,href:"/processing",tone:"bg-[#f2ecfa] text-[#936bd1]"},
];

type Rediscover={id:string;title:string;summary:string|null;location_label:string|null;reason:string;enrichment?:{image_url?:string|null;image_fit?:"cover"|"contain"}};
const REDISCOVER_TTL=10*60_000,MAINTENANCE_TTL=24*60*60_000;

export default function Home(){
  const router=useRouter(),cameraRef=useRef<HTMLInputElement|null>(null),libraryRef=useRef<HTMLInputElement|null>(null),recorderRef=useRef<MediaRecorder|null>(null),chunksRef=useRef<Blob[]>([]);
  const[item,setItem]=useState<Rediscover|null>(null),[captureOpen,setCaptureOpen]=useState(false),[photoOpen,setPhotoOpen]=useState(false),[ask,setAsk]=useState(""),[recording,setRecording]=useState(false),[transcribing,setTranscribing]=useState(false);

  useEffect(()=>{
    let active=true,idleTimer:ReturnType<typeof setTimeout>|null=null;
    warmAnonymousSession();warmKipuLocation();
    try{const cached=localStorage.getItem("kipu-rediscover");if(cached)setItem(JSON.parse(cached))}catch{}
    async function load(){try{const last=Number(localStorage.getItem("kipu-rediscover-at")||0);if(Date.now()-last<REDISCOVER_TTL)return;const session=await ensureAnonymousSession(),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),2500),r=await fetch("/api/rediscover",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`},signal:controller.signal});clearTimeout(timer);if(!r.ok)return;const d=await r.json();if(active&&d.item){setItem(d.item);try{localStorage.setItem("kipu-rediscover",JSON.stringify(d.item));localStorage.setItem("kipu-rediscover-at",String(Date.now()))}catch{}}}catch{}}
    async function maintenance(){try{const last=Number(localStorage.getItem("kipu-maintenance-at")||0);if(Date.now()-last<MAINTENANCE_TTL)return;const session=await ensureAnonymousSession(),headers={Authorization:`Bearer ${session.access_token}`};localStorage.setItem("kipu-maintenance-at",String(Date.now()));await Promise.allSettled(["/api/memory/backfill","/api/memory/graph-backfill","/api/place/backfill"].map(url=>fetch(url,{method:"POST",headers})))}catch{}}
    void load();const runIdle=()=>void maintenance();if("requestIdleCallback" in window)(window as Window&{requestIdleCallback:(cb:()=>void,o?:{timeout:number})=>number}).requestIdleCallback(runIdle,{timeout:4000});else idleTimer=setTimeout(runIdle,2500);
    return()=>{active=false;if(idleTimer)clearTimeout(idleTimer);recorderRef.current?.stream.getTracks().forEach(t=>t.stop())};
  },[]);

  useEffect(()=>{document.body.style.overflow=captureOpen||photoOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[captureOpen,photoOpen]);

  async function photoChosen(file?:File){if(!file)return;try{await saveCameraCapture(file);router.push("/camera?captured=1")}catch(e){console.error("Kipu camera capture persist failed",e);router.push("/camera?captureError=1")}finally{if(cameraRef.current)cameraRef.current.value="";if(libraryRef.current)libraryRef.current.value=""}}
  function choosePhotoSource(source:"camera"|"library"){setPhotoOpen(false);setTimeout(()=>source==="camera"?cameraRef.current?.click():libraryRef.current?.click(),0)}
  function askKipu(q=ask){const clean=q.trim();if(clean)router.push(`/search?q=${encodeURIComponent(clean)}`)}

  async function startAskVoice(){
    try{const stream=await navigator.mediaDevices.getUserMedia({audio:true}),preferred=["audio/webm;codecs=opus","audio/webm","audio/mp4"].find(t=>MediaRecorder.isTypeSupported(t)),recorder=preferred?new MediaRecorder(stream,{mimeType:preferred}):new MediaRecorder(stream);chunksRef.current=[];recorder.ondataavailable=e=>e.data.size&&chunksRef.current.push(e.data);recorder.onstop=()=>void finishAskVoice(recorder.mimeType||preferred||"audio/webm");recorder.start(250);recorderRef.current=recorder;setRecording(true)}catch{setRecording(false)}
  }
  function stopAskVoice(){const recorder=recorderRef.current;if(!recorder||recorder.state==="inactive")return;recorder.stop();recorder.stream.getTracks().forEach(t=>t.stop());setRecording(false);setTranscribing(true)}
  async function finishAskVoice(mime:string){try{const blob=new Blob(chunksRef.current,{type:mime}),form=new FormData();form.append("audio",new File([blob],"kipu-home-question.webm",{type:mime}));const r=await fetch("/api/transcribe",{method:"POST",body:form}),d=await r.json();if(!r.ok||!d.text)throw new Error();setAsk(d.text);setTranscribing(false);askKipu(d.text)}catch{setTranscribing(false)}}

  return <main className="mx-auto w-full max-w-[430px] overflow-x-hidden bg-[#fbfaf7] text-[#111]">
    <input ref={cameraRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>void photoChosen(e.target.files?.[0])}/>
    <input ref={libraryRef} type="file" accept="image/*" className="hidden" onChange={e=>void photoChosen(e.target.files?.[0])}/>
    <div className="px-5 pb-[max(8px,env(safe-area-inset-bottom))] pt-4">
      <div className="flex items-start justify-between"><KipuLogo compact/><button aria-label="Einstellungen" className="flex h-9 w-9 items-center justify-center rounded-full border border-[#ebe9e4] bg-white/90 shadow-[0_3px_12px_rgba(0,0,0,.04)]"><Settings className="h-4 w-4"/></button></div>
      <header className="mt-3"><h1 className="max-w-[310px] text-[24px] font-semibold leading-[1.04] tracking-[-0.035em]">Was möchtest du heute festhalten?</h1><div className="mt-3 flex flex-col items-center"><button onClick={()=>setCaptureOpen(true)} aria-label="Neue Erinnerung festhalten" className="relative flex h-[78px] w-[78px] items-center justify-center rounded-full bg-[#74a18f] text-white shadow-[0_12px_28px_rgba(116,161,143,.24)] active:scale-95"><span className="absolute inset-[-5px] rounded-full border border-[#74a18f]/15"/><Plus className="h-9 w-9" strokeWidth={1.7}/></button><button onClick={()=>setCaptureOpen(true)} className="mt-1.5 text-center text-[10.5px] font-medium text-black/42">Text, Sprache, Foto oder Datei</button></div></header>

      {item&&<section className="mt-3"><div className="mb-1.5 flex items-center justify-between"><p className="text-[12.5px] font-semibold">Kipu erinnert dich</p><Sparkles className="h-4 w-4 text-[#74a18f]"/></div><Link prefetch={false} href={`/ideas/${item.id}`} className="kipu-card flex gap-3 p-2.5"><div className="flex h-[56px] w-[56px] shrink-0 items-center justify-center overflow-hidden rounded-[13px] bg-[#edf3ef]">{item.enrichment?.image_url?<img src={item.enrichment.image_url} alt="" loading="lazy" decoding="async" className={`h-full w-full ${item.enrichment.image_fit==="contain"?"object-contain p-1":"object-cover"}`}/>:<Sparkles className="h-5 w-5 text-[#74a18f]"/>}</div><div className="min-w-0 flex-1 self-center"><h2 className="line-clamp-1 text-[11.5px] font-semibold">{item.title}</h2><p className="mt-1 line-clamp-2 text-[9px] leading-3.5 text-black/46">{item.reason}</p></div><ChevronRight className="self-center h-4 w-4 shrink-0 text-black/25"/></Link></section>}

      <section className="mt-3"><p className="mb-1.5 text-[12.5px] font-semibold">Schnellzugriff</p><div className="grid grid-cols-2 gap-2.5"><Link href="/nearby" className="rounded-[17px] border border-[#e9e8e3] bg-white p-2.5 shadow-[0_4px_16px_rgba(0,0,0,.03)] active:scale-[.985]"><div className="flex items-start justify-between gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-[9px] bg-[#e8f2ed] text-[#74a18f]"><MapPin className="h-3.5 w-3.5"/></span><ChevronRight className="mt-1 h-3.5 w-3.5 text-black/22"/></div><p className="mt-2 text-[10.5px] font-semibold">In deiner Nähe</p><p className="mt-0.5 text-[8px] leading-3 text-black/38">Gespeicherte Orte entdecken</p></Link><Link href="/ideas" className="rounded-[17px] border border-[#e9e8e3] bg-white p-2.5 shadow-[0_4px_16px_rgba(0,0,0,.03)] active:scale-[.985]"><div className="flex items-start justify-between gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-[9px] bg-[#e7edf2] text-[#657f92]"><Images className="h-3.5 w-3.5"/></span><ChevronRight className="mt-1 h-3.5 w-3.5 text-black/22"/></div><p className="mt-2 text-[10.5px] font-semibold">Sammlung</p><p className="mt-0.5 text-[8px] leading-3 text-black/38">Alle Erinnerungen durchsuchen</p></Link></div></section>

      <section className="mt-3 rounded-[18px] border border-[#e5e7e2] bg-[#f8faf7] p-3"><div className="mb-2 flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#e8f2ed] text-[#74a18f]"><MessageCircle className="h-3.5 w-3.5"/></span><div><p className="text-[12.5px] font-semibold">Frag Kipu</p><p className="text-[8.5px] text-black/38">Frag so, wie du dich daran erinnerst.</p></div></div><form onSubmit={e=>{e.preventDefault();askKipu()}} className="flex items-center gap-1.5 rounded-[15px] border border-[#e1e4de] bg-white p-1.5 pl-2.5 shadow-[0_4px_14px_rgba(0,0,0,.025)]"><input value={ask} onChange={e=>setAsk(e.target.value)} placeholder={recording?"Ich höre zu…":transcribing?"Kipu hört nach…":"Wie hiess das Restaurant im Engadin?"} className="min-w-0 flex-1 bg-transparent text-[10.5px] outline-none placeholder:text-black/28" disabled={recording||transcribing}/>{transcribing?<span className="flex h-8 w-8 items-center justify-center"><LoaderCircle className="h-4 w-4 animate-spin text-[#74a18f]"/></span>:recording?<button type="button" onClick={stopAskVoice} aria-label="Aufnahme stoppen" className="flex h-8 w-8 items-center justify-center rounded-full bg-black text-white"><Square className="h-3 w-3 fill-white"/></button>:<button type="button" onClick={()=>void startAskVoice()} aria-label="Frage sprechen" className="flex h-8 w-8 items-center justify-center rounded-full text-[#74a18f]"><Mic className="h-4.5 w-4.5"/></button>}<button type="submit" aria-label="Kipu fragen" className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#74a18f] text-white disabled:opacity-35" disabled={!ask.trim()||recording||transcribing}><ChevronRight className="h-4 w-4"/></button></form><div className="mt-2 flex gap-1.5 overflow-x-auto pb-0.5 [scrollbar-width:none]">{["Welche Bücher wollte ich lesen?","Was wurde mir empfohlen?","Was ist in meiner Nähe?"].map(q=><button key={q} onClick={()=>askKipu(q)} className="shrink-0 rounded-full bg-white px-2.5 py-1.5 text-[8.5px] text-black/55 shadow-[0_1px_4px_rgba(0,0,0,.03)]">{q}</button>)}</div></section>
    </div>

    {captureOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 px-5 backdrop-blur-[3px]" onClick={()=>setCaptureOpen(false)}><section className="w-full max-w-[390px] rounded-[28px] bg-[#fbfaf7] p-5 shadow-[0_24px_70px_rgba(0,0,0,.22)]" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#74a18f]">Neue Erinnerung</p><h2 className="mt-1.5 text-[21px] font-semibold leading-[1.08] tracking-[-.025em]">Wie möchtest du sie festhalten?</h2></div><button onClick={()=>setCaptureOpen(false)} className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#efeee9]"><X className="h-4 w-4"/></button></div><div className="mt-5 grid grid-cols-2 gap-3">{actions.map(({label,hint,icon:Icon,href,tone})=>label==="Foto"?<button type="button" key={label} onClick={()=>{setCaptureOpen(false);setPhotoOpen(true)}} className="min-h-[128px] rounded-[20px] border border-[#ecebe7] bg-white p-4 text-left shadow-[0_6px_18px_rgba(0,0,0,.04)] active:scale-[.985]"><span className={`flex h-11 w-11 items-center justify-center rounded-[14px] ${tone}`}><Icon className="h-5 w-5"/></span><p className="mt-3 text-[14px] font-semibold">{label}</p><p className="mt-1 text-[10px] leading-4 text-black/42">{hint}</p></button>:<Link href={href} key={label} onClick={()=>setCaptureOpen(false)} className="min-h-[128px] rounded-[20px] border border-[#ecebe7] bg-white p-4 shadow-[0_6px_18px_rgba(0,0,0,.04)] active:scale-[.985]"><span className={`flex h-11 w-11 items-center justify-center rounded-[14px] ${tone}`}><Icon className="h-5 w-5"/></span><p className="mt-3 text-[14px] font-semibold">{label}</p><p className="mt-1 text-[10px] leading-4 text-black/42">{hint}</p></Link>)}</div></section></div>}

    {photoOpen&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/30 px-5 backdrop-blur-[3px]" onClick={()=>setPhotoOpen(false)}><section className="w-full max-w-[350px] rounded-[26px] bg-[#fbfaf7] p-5 shadow-[0_24px_70px_rgba(0,0,0,.22)]" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-[19px] font-semibold tracking-[-.02em]">Foto hinzufügen</h2><button onClick={()=>setPhotoOpen(false)} className="flex h-9 w-9 items-center justify-center rounded-full bg-[#efeee9]"><X className="h-4 w-4"/></button></div><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>choosePhotoSource("camera")} className="rounded-[20px] border border-[#e8e7e2] bg-white p-4 text-left shadow-[0_5px_18px_rgba(0,0,0,.04)]"><span className="flex h-11 w-11 items-center justify-center rounded-[14px] bg-[#e8f3ee] text-[#5d9b84]"><Camera className="h-5 w-5"/></span><p className="mt-3 text-[14px] font-semibold">Kamera</p><p className="mt-1 text-[10px] leading-4 text-black/42">Neues Foto aufnehmen</p></button><button onClick={()=>choosePhotoSource("library")} className="rounded-[20px] border border-[#e8e7e2] bg-white p-4 text-left shadow-[0_5px_18px_rgba(0,0,0,.04)]"><span className="flex h-11 w-11 items-center justify-center rounded-[14px] bg-[#e7edf2] text-[#657f92]"><Images className="h-5 w-5"/></span><p className="mt-3 text-[14px] font-semibold">Fotobibliothek</p><p className="mt-1 text-[10px] leading-4 text-black/42">Vorhandenes Bild wählen</p></button></div></section></div>}
  </main>;
}
