"use client";

import { Filter, Home, LoaderCircle, Search, Sparkles, Trash2, UserRound } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ensureAnonymousSession, getSupabaseBrowserClient } from "@/lib/supabase-browser";

type IdeaRow = {id:string;title:string;summary:string|null;tags:string[];location_label:string|null;created_at:string;enrichment:{category?:string;image_url?:string|null;image_fit?:"cover"|"contain";processing_status?:"pending"|"processing"|"ready"|"failed"}};
type CategoryRow={id:string;parent_id:string|null;name:string;sort_order:number};
type AssignmentRow={idea_id:string;category_id:string};

function emojiFor(category?: string) {if(category==="Buch")return"📚";if(category==="Restaurant"||category==="Essen")return"🍽️";if(category==="Produkt")return"📦";if(category==="Idee")return"💡";if(category==="Film")return"🎬";return"📌"}

export default function IdeasPage(){
 const[ideas,setIdeas]=useState<IdeaRow[]>([]),[categories,setCategories]=useState<CategoryRow[]>([]),[assignments,setAssignments]=useState<AssignmentRow[]>([]);const[loading,setLoading]=useState(true),[deleting,setDeleting]=useState(false);const[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<string>("all");
 useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>|null=null;async function load(){try{await ensureAnonymousSession();const supabase=getSupabaseBrowserClient();const[ideaRes,categoryRes,assignmentRes]=await Promise.all([supabase.from("ideas").select("id,title,summary,tags,location_label,created_at,enrichment").order("created_at",{ascending:false}),supabase.from("categories").select("id,parent_id,name,sort_order").order("sort_order").order("name"),supabase.from("idea_categories").select("idea_id,category_id")]);if(ideaRes.error)throw ideaRes.error;if(categoryRes.error)throw categoryRes.error;if(assignmentRes.error)throw assignmentRes.error;if(!active)return;const next=(ideaRes.data??[]) as IdeaRow[];setIdeas(next);setCategories((categoryRes.data??[]) as CategoryRow[]);setAssignments((assignmentRes.data??[]) as AssignmentRow[]);setLoading(false);if(next.some(i=>i.enrichment?.processing_status==="pending"||i.enrichment?.processing_status==="processing"))timer=setTimeout(load,3000)}catch(e){if(active){setError(e instanceof Error?e.message:"Ideen konnten nicht geladen werden.");setLoading(false)}}}load();return()=>{active=false;if(timer)clearTimeout(timer)}},[]);
 const categoryById=useMemo(()=>new Map(categories.map(c=>[c.id,c])),[categories]);const assignmentByIdea=useMemo(()=>{const map=new Map<string,string[]>();for(const a of assignments){const list=map.get(a.idea_id)??[];list.push(a.category_id);map.set(a.idea_id,list)}return map},[assignments]);const mainCategories=useMemo(()=>categories.filter(c=>!c.parent_id),[categories]);
 const visibleIdeas=useMemo(()=>{if(selected==="all")return ideas;return ideas.filter(idea=>(assignmentByIdea.get(idea.id)??[]).some(id=>id===selected||categoryById.get(id)?.parent_id===selected))},[ideas,selected,assignmentByIdea,categoryById]);
 function displayCategory(ideaId:string){const ids=assignmentByIdea.get(ideaId)??[];if(!ids.length)return null;const chosen=ids.map(id=>categoryById.get(id)).filter(Boolean).sort((a,b)=>Number(Boolean(a?.parent_id))-Number(Boolean(b?.parent_id))).at(-1);return chosen?.name??null}
 async function deleteAllIdeas(){if(!ideas.length||deleting)return;if(!window.confirm(`Wirklich alle ${ideas.length} Ideen löschen? Das kann nicht rückgängig gemacht werden.`))return;setDeleting(true);setError(null);try{await ensureAnonymousSession();const supabase=getSupabaseBrowserClient();const{data:authData}=await supabase.auth.getUser();if(!authData.user)throw new Error("Keine aktive Session.");const{error}=await supabase.from("ideas").delete().eq("user_id",authData.user.id);if(error)throw error;setIdeas([]);setAssignments([])}catch(e){setError(e instanceof Error?e.message:"Ideen konnten nicht gelöscht werden.")}finally{setDeleting(false)}}
 return <main className="mx-auto flex min-h-screen w-full max-w-[430px] flex-col bg-[#fbfaf7] text-black"><header className="flex items-center justify-between px-5 pb-3 pt-7"><h1 className="text-[22px] font-semibold">Meine Ideen</h1><div className="flex items-center gap-4">{ideas.length>0&&<button onClick={deleteAllIdeas} disabled={deleting} aria-label="Alle Ideen löschen" className="text-[#c63f35] disabled:opacity-40">{deleting?<LoaderCircle className="h-5 w-5 animate-spin"/>:<Trash2 className="h-5 w-5"/>}</button>}<Filter className="h-5 w-5"/><Link href="/search"><Search className="h-5 w-5"/></Link></div></header>
 <div className="flex gap-2 overflow-x-auto px-4 pb-4 [scrollbar-width:none]"><button onClick={()=>setSelected("all")} className={`whitespace-nowrap rounded-full px-4 py-2 text-[12px] ${selected==="all"?"bg-black text-white":"bg-[#f0efeb]"}`}>Alle</button>{mainCategories.map(c=><button key={c.id} onClick={()=>setSelected(c.id)} className={`whitespace-nowrap rounded-full px-4 py-2 text-[12px] ${selected===c.id?"bg-black text-white":"bg-[#f0efeb]"}`}>{c.name}</button>)}</div>
 <section className="border-t border-black/5 px-4 pt-4">{loading&&<div className="flex justify-center py-16"><LoaderCircle className="h-6 w-6 animate-spin"/></div>}{error&&<div className="rounded-[14px] bg-[#fff0ef] p-4 text-[12px] text-[#9f3731]">{error}</div>}{!loading&&!error&&ideas.length===0&&<div className="py-16 text-center"><p className="text-[14px] font-medium">Noch keine Ideen gespeichert.</p><p className="mt-2 text-[12px] text-black/45">Auf dem Homescreen kannst du deine erste Erinnerung erfassen.</p></div>}{!loading&&!error&&ideas.length>0&&visibleIdeas.length===0&&<div className="py-12 text-center text-[13px] text-black/45">In dieser Kategorie ist noch nichts gespeichert.</div>}{!loading&&visibleIdeas.length>0&&<div className="space-y-2">{visibleIdeas.map(idea=>{const legacyCategory=idea.enrichment?.category,image=idea.enrichment?.image_url,fit=idea.enrichment?.image_fit??"cover",status=idea.enrichment?.processing_status,processing=status==="pending"||status==="processing",failed=status==="failed",date=new Date(idea.created_at).toLocaleDateString("de-CH"),categoryName=displayCategory(idea.id);return <Link href={`/ideas/${idea.id}`} key={idea.id} className="flex gap-3 rounded-[14px] bg-white p-2 shadow-[0_2px_10px_rgba(0,0,0,.06)]"><div className="flex h-[82px] w-[88px] shrink-0 items-center justify-center overflow-hidden rounded-[10px] bg-[#e8ece4] text-[30px]">{image?<img src={image} alt="" className={`h-full w-full ${fit==="contain"?"object-contain p-1":"object-cover"}`} referrerPolicy="no-referrer"/>:processing?<Sparkles className="h-7 w-7 animate-pulse text-[#7378db]"/>:emojiFor(legacyCategory)}</div><div className="min-w-0 flex-1 py-1"><h2 className="line-clamp-2 text-[15px] font-semibold leading-5">{idea.title}</h2>{processing?<p className="mt-1 flex items-center gap-1.5 text-[12px] text-[#696fc6]"><LoaderCircle className="h-3 w-3 animate-spin"/>Kipu ergänzt Details…</p>:failed?<p className="mt-1 text-[12px] text-[#a33b34]">Gespeichert · Aufbereitung offen</p>:<p className="mt-1 line-clamp-1 text-[12px] text-black/55">{idea.location_label||idea.summary||"Gespeicherte Idee"}</p>}<p className="mt-1 text-[11px] text-black/40">{date}</p><div className="mt-1 text-right">{!processing&&(categoryName||legacyCategory||idea.tags?.[0])&&<span className="rounded-full bg-[#f0efeb] px-2 py-1 text-[10px]">{categoryName||legacyCategory||idea.tags[0]}</span>}</div></div></Link>})}</div>}</section>
 <nav className="mt-auto flex items-center justify-around border-t border-black/5 bg-white px-14 py-4"><Link href="/" className="rounded-full bg-white px-6 py-3 shadow-[0_3px_14px_rgba(0,0,0,.10)]"><Home className="h-5 w-5 fill-black"/></Link><UserRound className="h-5 w-5"/></nav></main>}
