export type DuplicateConfidence="none"|"possible"|"high";
export type IdentityIdentifier={type:string;value:string};
export type IdentityInput={id?:string|null;title?:string|null;summary?:string|null;original_input?:string|null;tags?:string[]|null;people?:string[]|null;location_label?:string|null;canonical_name?:string|null;urls?:string[]|null;identifiers?:IdentityIdentifier[]|null;latitude?:number|null;longitude?:number|null;enrichment?:any};
export type DeterministicMatch={confidence:DuplicateConfidence;score:number;reasons:string[];matchers:string[]};
const TRACKING=/^(utm_.+|fbclid|gclid|gbraid|wbraid|mc_cid|mc_eid|ref|ref_|source)$/i;
export function normalizeText(v:any){return String(v??"").toLocaleLowerCase("de-CH").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim()}
export function normalizeUrl(value:any){try{const u=new URL(String(value).trim());u.hash="";for(const key of [...u.searchParams.keys()])if(TRACKING.test(key))u.searchParams.delete(key);u.hostname=u.hostname.toLowerCase().replace(/^www\./,"");u.pathname=u.pathname.replace(/\/+$/,"")||"/";const params=[...u.searchParams.entries()].sort(([a],[b])=>a.localeCompare(b));u.search="";for(const[k,v]of params)u.searchParams.append(k,v);return u.toString()}catch{return null}}
function urlsFromText(v:any){return String(v??"").match(/https?:\/\/[^\s<>"')\]]+/gi)??[]}
function cleanId(v:any){return String(v??"").toUpperCase().replace(/[^A-Z0-9]/g,"")}
function isbn13(v:string){const x=cleanId(v).replace(/X$/,"X");return x.length===10||x.length===13?x:null}
function gtin(v:string){const x=cleanId(v);return /^\d{8}$|^\d{12,14}$/.test(x)?x:null}
export function extractIdentity(input:IdentityInput){const e=input.enrichment??{},facts=[...(e.facts??[])],links=[...(e.useful_links??[]),...(e.sources??[])];const urls=new Set<string>();for(const raw of [...(input.urls??[]),...links.map((x:any)=>x?.url),...urlsFromText(input.original_input),...urlsFromText(input.summary)]){const n=normalizeUrl(raw);if(n)urls.add(n)}const ids=new Map<string,string>();const add=(type:any,value:any)=>{const t=normalizeText(type).replace(/ /g,"_");const v=cleanId(value);if(t&&v)ids.set(`${t}:${v}`,v)};for(const x of input.identifiers??[])add(x.type,x.value);for(const f of facts){const label=normalizeText(f?.label),value=String(f?.value??"");if(/isbn/.test(label)){const v=isbn13(value);if(v)add("isbn",v)}if(/ean|gtin|barcode/.test(label)){const v=gtin(value);if(v)add("gtin",v)}if(/(^| )id$|produkt id|product id|entity id|imdb|tmdb|spotify id|osm id|place id/.test(label))add(label,value)}const c=e.subject_coordinates??{};const latitude=Number.isFinite(input.latitude)?Number(input.latitude):Number.isFinite(c.latitude)?Number(c.latitude):null,longitude=Number.isFinite(input.longitude)?Number(input.longitude):Number.isFinite(c.longitude)?Number(c.longitude):null;return{canonical_name:normalizeText(input.canonical_name||e.canonical_name||input.title||input.location_label),urls:[...urls],identifiers:[...ids.keys()],latitude,longitude}}
export function distanceMeters(aLat:number,aLon:number,bLat:number,bLon:number){const r=6371000,rad=(x:number)=>x*Math.PI/180,dLat=rad(bLat-aLat),dLon=rad(bLon-aLon),q=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(q)))}
function sameHostPath(a:string,b:string){try{const x=new URL(a),y=new URL(b);return x.hostname===y.hostname&&x.pathname===y.pathname}catch{return false}}
export function deterministicIdentityMatch(a:IdentityInput,b:IdentityInput):DeterministicMatch{const A=extractIdentity(a),B=extractIdentity(b),reasons:string[]=[],matchers:string[]=[];let score=0;const urlMatch=A.urls.find(x=>B.urls.includes(x));if(urlMatch){score=100;matchers.push("normalized_url");reasons.push("same normalized URL")}else if(A.urls.some(x=>B.urls.some(y=>sameHostPath(x,y)))){score=Math.max(score,96);matchers.push("canonical_url");reasons.push("same canonical web resource")}
const idMatch=A.identifiers.find(x=>B.identifiers.includes(x));if(idMatch){score=100;matchers.push("external_identifier");reasons.push(`same ${idMatch.split(":")[0]}`)}
if(A.latitude!=null&&A.longitude!=null&&B.latitude!=null&&B.longitude!=null){const d=distanceMeters(A.latitude,A.longitude,B.latitude,B.longitude);if(d<=20){score=Math.max(score,88);matchers.push("same_place_coordinates");reasons.push(`coordinates within ${Math.round(d)}m`)}else if(d<=60&&A.canonical_name&&B.canonical_name&&(A.canonical_name===B.canonical_name||A.canonical_name.includes(B.canonical_name)||B.canonical_name.includes(A.canonical_name))){score=Math.max(score,94);matchers.push("same_place_name_coordinates");reasons.push(`same place identity within ${Math.round(d)}m`)}}
if(A.canonical_name&&B.canonical_name&&A.canonical_name===B.canonical_name){score=Math.max(score,55);matchers.push("canonical_name");reasons.push("same canonical name")}
const confidence:DuplicateConfidence=score>=94?"high":score>=55?"possible":"none";return{confidence,score,reasons,matchers}}
export function compactIdentityCandidate(x:IdentityInput){const e=x.enrichment??{};return{id:x.id,title:x.title,summary:x.summary,original_input:x.original_input,tags:x.tags,people:x.people,location_label:x.location_label,facts:e.facts??[],useful_links:e.useful_links??[],subject_coordinates:e.subject_coordinates??null,memory:e.memory??null,identity:extractIdentity(x)}}
