import { createClient, type SupabaseClient } from "@supabase/supabase-js";
const BUCKET="idea-images",MAX_BYTES=8_000_000,INLINE_FALLBACK_MAX_BYTES=5_000_000;
function extensionForMime(type:string){const mime=type.toLowerCase().split(";")[0].trim();if(mime==="image/png")return"png";if(mime==="image/webp")return"webp";if(mime==="image/gif")return"gif";return"jpg"}
function decodeDataUrl(value:string){const match=value.match(/^data:(image\/(?:jpeg|jpg|png|webp|gif));base64,(.+)$/i);if(!match)return null;const bytes=Buffer.from(match[2],"base64");if(!bytes.length||bytes.length>MAX_BYTES)return null;return{bytes,contentType:match[1].toLowerCase()}}
async function fetchImageAttempt(value:string,headers:Record<string,string>){try{const response=await fetch(value,{redirect:"follow",headers,signal:AbortSignal.timeout(15000),cache:"no-store"});if(!response.ok)return{ok:false as const,reason:`http_${response.status}`};const contentType=(response.headers.get("content-type")||"").toLowerCase().split(";")[0].trim();if(!contentType.startsWith("image/"))return{ok:false as const,reason:`not_image:${contentType||"unknown"}`};const bytes=Buffer.from(await response.arrayBuffer());if(!bytes.length||bytes.length>MAX_BYTES)return{ok:false as const,reason:"too_large_or_empty"};return{ok:true as const,bytes,contentType}}catch(error){return{ok:false as const,reason:error instanceof Error?error.message:"fetch_failed"}}}
async function downloadImage(value:string){if(value.startsWith("data:image/"))return decodeDataUrl(value);let parsed:URL;try{parsed=new URL(value)}catch{return null}const headers={"User-Agent":"Mozilla/5.0 Kipu/1.0",Accept:"image/*","Accept-Language":"de-CH,de;q=0.9,en;q=0.7"};const first=await fetchImageAttempt(value,headers);if(first.ok)return{bytes:first.bytes,contentType:first.contentType};const second=await fetchImageAttempt(value,{...headers,Referer:`${parsed.protocol}//${parsed.host}/`});if(second.ok)return{bytes:second.bytes,contentType:second.contentType};return null}
function storageClient(fallback:SupabaseClient){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!serviceRoleKey)return fallback;return createClient(url,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}})}
async function writeEnrichment(supabase:SupabaseClient,userId:string,ideaId:string,enrichment:Record<string,any>){const{error}=await supabase.from("ideas").update({enrichment}).eq("id",ideaId).eq("user_id",userId);if(error)throw error}
export async function persistIdeaHeroImage(supabase:SupabaseClient,userId:string,ideaId:string){const{data:idea,error}=await supabase.from("ideas").select("enrichment").eq("id",ideaId).eq("user_id",userId).single();if(error||!idea)throw error??new Error("idea_not_found_for_image_storage");const enrichment=(idea.enrichment??{}) as Record<string,any>,imageUrl=typeof enrichment.image_url==="string"?enrichment.image_url:null;if(!imageUrl)return{stored:false,reason:"no_image"};if(imageUrl.includes(`/storage/v1/object/public/${BUCKET}/`))return{stored:true,url:imageUrl,reason:"already_stored"};const downloaded=await downloadImage(imageUrl);if(!downloaded)return{stored:false,reason:"download_failed"};const ext=extensionForMime(downloaded.contentType),path=`${userId}/${ideaId}/hero.${ext}`,writer=storageClient(supabase);const{error:uploadError}=await writer.storage.from(BUCKET).upload(path,downloaded.bytes,{contentType:downloaded.contentType,upsert:true,cacheControl:"31536000"});if(uploadError){const message=`${(uploadError as any)?.message??""} ${(uploadError as any)?.code??""}`.toLowerCase();if(downloaded.bytes.length<=INLINE_FALLBACK_MAX_BYTES){const inlineUrl=`data:${downloaded.contentType};base64,${downloaded.bytes.toString("base64")}`;await writeEnrichment(supabase,userId,ideaId,{...enrichment,image_url:inlineUrl,image_source_url:imageUrl.startsWith("data:image/")?null:imageUrl,image_storage_fallback:"inline_data_url",image_storage_error:message.slice(0,180),image_stored_at:new Date().toISOString()});return{stored:true,url:"inline-data-url",reason:"storage_blocked_inline_fallback"}}throw uploadError}const{data:publicData}=writer.storage.from(BUCKET).getPublicUrl(path),stableUrl=publicData.publicUrl;await writeEnrichment(supabase,userId,ideaId,{...enrichment,image_url:stableUrl,image_storage_path:path,image_source_url:imageUrl.startsWith("data:image/")?null:imageUrl,image_storage_fallback:null,image_storage_error:null,image_stored_at:new Date().toISOString()});return{stored:true,url:stableUrl,path,via:writer===supabase?"user":"service_role"}}
