import type { SupabaseClient } from "@supabase/supabase-js";
import { searchImages } from "@/lib/kipu-agent-tools";

const planSchema={type:"object",additionalProperties:false,properties:{mode:{type:"string",enum:["exact_entity","representative"]},search_query:{type:"string"},generation_prompt:{type:"string"}},required:["mode","search_query","generation_prompt"]};

function responseText(payload:any){if(typeof payload?.output_text==="string"&&payload.output_text.trim())return payload.output_text;for(const output of payload?.output??[])for(const content of output?.content??[])if(typeof content?.text==="string"&&content.text.trim())return content.text;return null}

async function makePlan(openAiKey:string,context:Record<string,unknown>){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:[{role:"user",content:[{type:"input_text",text:`Entscheide für das Hero-Bild einer persönlichen Ideen-App genau zwischen zwei Modi.\n\nIdee: ${JSON.stringify(context)}\n\nexact_entity: eine konkrete reale Sache ist gespeichert, z.B. bestimmtes Buch, Restaurant, Hotel, Produkt, Film, Webseite, Person oder eindeutig benannter Ort. Dann soll ein echtes Bild genau dieser Entität verwendet werden. search_query ist eine einzige präzise Bildsuche. generation_prompt bleibt leer.\n\nrepresentative: Vorhaben, Wunsch, Aktivität, Interesse oder abstrakte Idee. Dann KEINE Web-Bildsuche. Erzeuge stattdessen einen einzigen hochwertigen Bildprompt, der die emotionale Essenz der Idee als attraktives, natürliches, fotografisches Hero-Bild zeigt. Keine Schrift im Bild. Keine Logos. Keine zufälligen Personen, ausser Menschen sind für die Idee zwingend zentral. Keine Schnappschussästhetik. Bevorzuge klare Hauptmotive, schöne Komposition, Atmosphäre, Natur, charakteristische Objekte oder Tiere. Das Bild soll auf einem Smartphone sofort schön und erinnerungsstark wirken.`}]}],text:{format:{type:"json_schema",name:"kipu_hero_plan",strict:true,schema:planSchema}}})});if(!response.ok)throw new Error(`hero_plan_${response.status}`);const raw=responseText(await response.json());if(!raw)throw new Error("hero_plan_no_output");return JSON.parse(raw) as {mode:"exact_entity"|"representative";search_query:string;generation_prompt:string}}

async function generateImage(openAiKey:string,prompt:string){const response=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-image-2",prompt,size:"1536x1024",quality:"medium",n:1})});if(!response.ok){const detail=(await response.text()).slice(0,500);throw new Error(`hero_generation_${response.status}:${detail}`)}const payload=await response.json() as any;const item=payload?.data?.[0];if(typeof item?.b64_json==="string"&&item.b64_json)return `data:image/png;base64,${item.b64_json}`;if(typeof item?.url==="string"&&item.url)return item.url;throw new Error("hero_generation_no_image")}

export async function curateIdeaHeroImage(supabase:SupabaseClient,userId:string,openAiKey:string,ideaId:string){const{data:idea,error}=await supabase.from("ideas").select("id,title,summary,tags,location_label,enrichment,input_type").eq("id",ideaId).eq("user_id",userId).single();if(error||!idea)throw error??new Error("idea_not_found_for_image_curation");const enrichment=(idea.enrichment??{}) as Record<string,any>;if(enrichment.input_image_used||idea.input_type==="camera")return{changed:false,reason:"user_image_preferred"};const context={title:idea.title,summary:idea.summary,tags:idea.tags??[],location:idea.location_label,category:enrichment.category??null,facts:enrichment.facts??[]};const plan=await makePlan(openAiKey,context);let imageUrl:string|null=null;let reason="";
if(plan.mode==="exact_entity"){if(typeof enrichment.image_url==="string"&&enrichment.image_url&&!enrichment.image_url.startsWith("data:image/")){imageUrl=enrichment.image_url;reason="exact_entity_existing"}else{const result:any=await searchImages(plan.search_query||String(idea.title),{supabase,userId,openAiKey,currentIdeaId:ideaId});const candidate=(result?.candidates??[])[0];imageUrl=typeof candidate?.url==="string"?candidate.url:null;reason=imageUrl?"exact_entity_single_search":"exact_entity_no_image"}}
else{imageUrl=await generateImage(openAiKey,plan.generation_prompt||`Beautiful editorial photograph representing: ${idea.title}. Natural, memorable, no text, no logos.`);reason="representative_generated"}
if(!imageUrl)return{changed:false,reason,plan};const nextEnrichment={...enrichment,image_url:imageUrl,image_fit:"cover",image_reason:reason,image_curation_version:4,image_visual_mode:plan.mode,image_generation_model:plan.mode==="representative"?"gpt-image-2":null};const{error:updateError}=await supabase.from("ideas").update({enrichment:nextEnrichment}).eq("id",ideaId).eq("user_id",userId);if(updateError)throw updateError;return{changed:true,reason,plan}}
