import type { SupabaseClient } from "@supabase/supabase-js";
import { searchPlaces } from "@/lib/kipu-agent-tools";

const schema={type:"object",additionalProperties:false,properties:{is_physical_place:{type:"boolean"},canonical_name:{anyOf:[{type:"string"},{type:"null"}]},street_address:{anyOf:[{type:"string"},{type:"null"}]},locality:{anyOf:[{type:"string"},{type:"null"}]},review_rating:{anyOf:[{type:"string"},{type:"null"}]},review_count:{anyOf:[{type:"string"},{type:"null"}]},review_summary:{anyOf:[{type:"string"},{type:"null"}]},official_url:{anyOf:[{type:"string"},{type:"null"}]},reviews_url:{anyOf:[{type:"string"},{type:"null"}]}},required:["is_physical_place","canonical_name","street_address","locality","review_rating","review_count","review_summary","official_url","reviews_url"]};
function textOf(p:any){if(typeof p.output_text==="string")return p.output_text;for(const o of p.output??[])for(const c of o.content??[])if(typeof c?.text==="string")return c.text;return null}
function validHttp(v:any){try{const u=new URL(String(v));return /^https?:$/.test(u.protocol)?u.toString():null}catch{return null}}
function mergeLinks(a:any[]=[],b:any[]=[]){const out:any[]=[],seen=new Set<string>();for(const x of [...a,...b]){const u=validHttp(x?.url);if(u&&!seen.has(u)){seen.add(u);out.push({...x,url:u})}}return out.slice(0,4)}
function mergeFacts(a:any[]=[],b:any[]=[]){const out:any[]=[],seen=new Set<string>();for(const x of [...a,...b]){const k=String(x?.label??"").trim().toLowerCase();if(k&&!seen.has(k)&&x?.value){seen.add(k);out.push(x)}}return out.slice(0,7)}
function meters(aLat:number,aLon:number,bLat:number,bLon:number){const r=6371000,toRad=(v:number)=>v*Math.PI/180,dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon),x=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLon/2)**2;return 2*r*Math.asin(Math.min(1,Math.sqrt(x)))}
function norm(v:any){return String(v??"").toLocaleLowerCase("de-CH").normalize("NFKD").replace(/[^a-z0-9äöü]+/g," ").trim()}
async function geocodeCandidate(queries:string[],latitude?:number|null,longitude?:number|null){for(const q of queries.map(x=>x.trim()).filter(Boolean)){const found:any=await searchPlaces(q,Number.isFinite(latitude)?Number(latitude):undefined,Number.isFinite(longitude)?Number(longitude):undefined);const results=Array.isArray(found?.results)?found.results:[];const hit=results.find((x:any)=>Number.isFinite(x?.latitude)&&Number.isFinite(x?.longitude));if(hit)return{hit,query:q}}return null}

async function findSamePlace(s:SupabaseClient,userId:string,ideaId:string,label:string,lat:number,lon:number){
 const{data,error}=await s.from("ideas").select("id,title,location_label,enrichment,created_at").eq("user_id",userId).neq("id",ideaId).order("created_at",{ascending:false}).limit(100);if(error)return null;
 const current=norm(label),currentWords=new Set(current.split(/\s+/).filter(w=>w.length>2));
 let best:any=null;
 for(const row of data??[]){const e=(row.enrichment??{}) as Record<string,any>,c=e.subject_coordinates;if(!Number.isFinite(c?.latitude)||!Number.isFinite(c?.longitude))continue;const d=meters(lat,lon,Number(c.latitude),Number(c.longitude));if(d>80)continue;const other=norm(row.location_label||row.title),otherWords=new Set(other.split(/\s+/).filter(w=>w.length>2));let shared=0;for(const w of currentWords)if(otherWords.has(w))shared++;const nameMatch=current&&other&&(current.includes(other)||other.includes(current)||shared>=1);if(!nameMatch&&d>25)continue;const score=(d<=25?3:d<=50?2:1)+(nameMatch?2:0);if(!best||score>best.score)best={row,d,score};}
 return best;
}

export async function ensurePlaceEnrichment(s:SupabaseClient,userId:string,openAiKey:string,ideaId:string){
 const{data:idea,error}=await s.from("ideas").select("id,title,summary,original_input,tags,latitude,longitude,location_label,enrichment").eq("id",ideaId).eq("user_id",userId).single();if(error||!idea)throw error??new Error("idea_not_found");
 const e=(idea.enrichment??{}) as Record<string,any>;if(e.processing_status!=="ready")return{updated:false,reason:"not_ready"};
 const captureLat=Number.isFinite(idea.latitude)?Number(idea.latitude):Number.isFinite(e.capture_location?.latitude)?Number(e.capture_location.latitude):null,captureLon=Number.isFinite(idea.longitude)?Number(idea.longitude):Number.isFinite(e.capture_location?.longitude)?Number(e.capture_location.longitude):null;
 const inputImage=typeof e.input_image==="string"&&e.input_image.startsWith("data:image/")?e.input_image:null;
 const userContent:any[]=[{type:"input_text",text:JSON.stringify({title:idea.title,summary:idea.summary,original_input:idea.original_input,tags:idea.tags,location_label:idea.location_label,capture_location:Number.isFinite(captureLat)&&Number.isFinite(captureLon)?{latitude:captureLat,longitude:captureLon}:null})}];if(inputImage)userContent.push({type:"input_image",image_url:inputImage,detail:"high"});
 const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:[{role:"system",content:[{type:"input_text",text:"Du bist Kipus Place-Resolver. Entscheide, ob die gespeicherte Erinnerung eine konkrete öffentlich auffindbare physische Location/POI meint. Nutze bei Foto-Captures das Bild zur Entitätsidentifikation. Aufnahme-GPS ist ein Such-/Disambiguierungshinweis, aber nicht automatisch die Subject Location. Wenn eine konkrete Location gemeint ist, identifiziere die konkrete Entität und recherchiere kanonischen Namen, möglichst genaue Strassenadresse und Ort. Recherchiere ausserdem öffentlich verfügbare aktuelle Basisdaten. review_rating/review_count nur angeben, wenn sie aus einer auffindbaren Quelle plausibel gestützt sind. review_summary fasst typische öffentlich sichtbare Rezensionstendenzen in höchstens einem kurzen Satz zusammen; nichts erfinden. official_url nur offizielle Seite. reviews_url soll eine konkrete öffentliche Bewertungs-/Listingseite sein, falls auffindbar. Wenn keine konkrete physische Entität gemeint ist, is_physical_place=false und die übrigen Felder null."}]},{role:"user",content:userContent}],text:{format:{type:"json_schema",name:"kipu_place_resolution",strict:true,schema}}})});if(!r.ok)throw new Error(`place_openai_${r.status}`);const raw=textOf(await r.json());if(!raw)throw new Error("place_no_output");const p=JSON.parse(raw);if(!p.is_physical_place||!p.canonical_name){console.info("Kipu place resolver",{ideaId,result:"not_place",title:idea.title});return{updated:false,reason:"not_place"}};
 const queries=[
  [p.canonical_name,p.street_address,p.locality].filter(Boolean).join(", "),
  [p.street_address,p.locality].filter(Boolean).join(", "),
  [p.canonical_name,p.locality].filter(Boolean).join(", "),
  String(p.canonical_name??""),
  String(p.street_address??""),
 ];
 const geo=await geocodeCandidate(queries,captureLat,captureLon);if(!geo){console.info("Kipu place resolver",{ideaId,result:"no_coordinates",canonical_name:p.canonical_name,street_address:p.street_address,locality:p.locality,queries});return{updated:false,reason:"no_coordinates"}};
 const first:any=geo.hit,lat=Number(first.latitude),lon=Number(first.longitude),label=[p.canonical_name,p.locality].filter(Boolean).join(", ")||first.displayName;const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([p.canonical_name,p.street_address,p.locality].filter(Boolean).join(" "))}`;
 const facts:any[]=[];if(p.street_address)facts.push({label:"Adresse",value:String(p.street_address)});if(p.review_rating)facts.push({label:"Bewertung",value:p.review_count?`${p.review_rating} (${p.review_count})`:p.review_rating});if(p.review_summary)facts.push({label:"Rezensionen",value:p.review_summary});if(first.openingHours)facts.push({label:"Öffnungszeiten",value:String(first.openingHours)});if(first.phone)facts.push({label:"Telefon",value:String(first.phone)});
 const links:any[]=[{label:"Google Maps",url:maps}];const official=validHttp(p.official_url)||validHttp(first.website);if(official)links.push({label:"Website",url:official});const reviews=validHttp(p.reviews_url);if(reviews)links.push({label:"Rezensionen",url:reviews});
 const duplicate=await findSamePlace(s,userId,ideaId,label,lat,lon),de=duplicate?.row?.enrichment??{};
 const enrichment={...e,subject_coordinates:{latitude:lat,longitude:lon},facts:mergeFacts(facts,mergeFacts(de.facts??[],e.facts??[])),useful_links:mergeLinks(links,mergeLinks(de.useful_links??[],e.useful_links??[])),duplicate_of_idea_id:e.duplicate_of_idea_id??duplicate?.row?.id??null,duplicate_confidence:e.duplicate_confidence&&e.duplicate_confidence!=="none"?e.duplicate_confidence:duplicate?"high":"none",place_enriched_at:new Date().toISOString(),place_enrichment_version:3,place_geocode_query:geo.query};
 const u=await s.from("ideas").update({location_label:label,location_source:"researched",enrichment}).eq("id",ideaId).eq("user_id",userId);if(u.error)throw u.error;console.info("Kipu place resolver",{ideaId,result:"updated",label,lat,lon,query:geo.query,duplicateOf:duplicate?.row?.id??null,duplicateDistance:duplicate?.d??null});return{updated:true,latitude:lat,longitude:lon,label,duplicate_of_idea_id:duplicate?.row?.id??null}
}
