import type { SupabaseClient } from "@supabase/supabase-js";
import { searchPlaces } from "@/lib/kipu-agent-tools";

const schema={type:"object",additionalProperties:false,properties:{is_physical_place:{type:"boolean"},canonical_name:{anyOf:[{type:"string"},{type:"null"}]},locality:{anyOf:[{type:"string"},{type:"null"}]},review_rating:{anyOf:[{type:"string"},{type:"null"}]},review_count:{anyOf:[{type:"string"},{type:"null"}]},review_summary:{anyOf:[{type:"string"},{type:"null"}]},official_url:{anyOf:[{type:"string"},{type:"null"}]},reviews_url:{anyOf:[{type:"string"},{type:"null"}]}},required:["is_physical_place","canonical_name","locality","review_rating","review_count","review_summary","official_url","reviews_url"]};
function textOf(p:any){if(typeof p.output_text==="string")return p.output_text;for(const o of p.output??[])for(const c of o.content??[])if(typeof c?.text==="string")return c.text;return null}
function validHttp(v:any){try{const u=new URL(String(v));return /^https?:$/.test(u.protocol)?u.toString():null}catch{return null}}
function mergeLinks(a:any[]=[],b:any[]=[]){const out:any[]=[],seen=new Set<string>();for(const x of [...a,...b]){const u=validHttp(x?.url);if(u&&!seen.has(u)){seen.add(u);out.push({...x,url:u})}}return out.slice(0,4)}
function mergeFacts(a:any[]=[],b:any[]=[]){const out:any[]=[],seen=new Set<string>();for(const x of [...a,...b]){const k=String(x?.label??"").trim().toLowerCase();if(k&&!seen.has(k)&&x?.value){seen.add(k);out.push(x)}}return out.slice(0,7)}

export async function ensurePlaceEnrichment(s:SupabaseClient,userId:string,openAiKey:string,ideaId:string){
 const{data:idea,error}=await s.from("ideas").select("id,title,summary,original_input,tags,location_label,enrichment").eq("id",ideaId).eq("user_id",userId).single();if(error||!idea)throw error??new Error("idea_not_found");
 const e=(idea.enrichment??{}) as Record<string,any>;if(e.processing_status!=="ready")return{updated:false,reason:"not_ready"};
 const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:[{role:"system",content:[{type:"input_text",text:"Du bist Kიპus Place-Resolver. Entscheide, ob die gespeicherte Erinnerung eine konkrete öffentlich auffindbare physische Location/POI meint (z.B. Lokal, Museum, Hotel, Geschäft, Sehenswürdigkeit, Anlage; Beispiele sind nicht abschliessend). Wenn ja, identifiziere die konkrete Entität und recherchiere öffentlich verfügbare aktuelle Basisdaten. review_rating/review_count nur angeben, wenn sie aus einer auffindbaren Quelle plausibel gestützt sind. review_summary fasst typische öffentlich sichtbare Rezensionstendenzen in höchstens einem kurzen Satz zusammen; nichts erfinden. official_url nur offizielle Seite. reviews_url soll eine konkrete öffentliche Bewertungs-/Listingseite sein, falls auffindbar. Wenn keine konkrete physische Entität gemeint ist, is_physical_place=false und die übrigen Felder null."}]},{role:"user",content:[{type:"input_text",text:JSON.stringify({title:idea.title,summary:idea.summary,original_input:idea.original_input,tags:idea.tags,location_label:idea.location_label})}]}],text:{format:{type:"json_schema",name:"kipu_place_resolution",strict:true,schema}}})});if(!r.ok)throw new Error(`place_openai_${r.status}`);const raw=textOf(await r.json());if(!raw)throw new Error("place_no_output");const p=JSON.parse(raw);if(!p.is_physical_place||!p.canonical_name)return{updated:false,reason:"not_place"};
 const q=[p.canonical_name,p.locality].filter(Boolean).join(", ");const found:any=await searchPlaces(q);const first=Array.isArray(found?.results)?found.results[0]:null;if(!first||!Number.isFinite(first.latitude)||!Number.isFinite(first.longitude))return{updated:false,reason:"no_coordinates"};
 const lat=Number(first.latitude),lon=Number(first.longitude),label=[p.canonical_name,p.locality].filter(Boolean).join(", ")||first.displayName;const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.canonical_name} ${p.locality??""}`.trim())}`;
 const facts:any[]=[];if(p.review_rating)facts.push({label:"Bewertung",value:p.review_count?`${p.review_rating} (${p.review_count})`:p.review_rating});if(p.review_summary)facts.push({label:"Rezensionen",value:p.review_summary});if(first.openingHours)facts.push({label:"Öffnungszeiten",value:String(first.openingHours)});if(first.phone)facts.push({label:"Telefon",value:String(first.phone)});
 const links:any[]=[{label:"Google Maps",url:maps}];const official=validHttp(p.official_url)||validHttp(first.website);if(official)links.push({label:"Website",url:official});const reviews=validHttp(p.reviews_url);if(reviews)links.push({label:"Rezensionen",url:reviews});
 const enrichment={...e,subject_coordinates:{latitude:lat,longitude:lon},facts:mergeFacts(facts,e.facts??[]),useful_links:mergeLinks(links,e.useful_links??[]),place_enriched_at:new Date().toISOString(),place_enrichment_version:1};const u=await s.from("ideas").update({location_label:label,location_source:"researched",enrichment}).eq("id",ideaId).eq("user_id",userId);if(u.error)throw u.error;return{updated:true,latitude:lat,longitude:lon,label}
}
