import type { Idea } from "@/types/idea";

export const mockIdeas: Idea[] = [
  {
    id: "grillstelle-wald",
    originalInput: "Coole Grillstelle hier im Wald, unbedingt für später merken.",
    inputType: "camera",
    title: "Grillstelle im Wald",
    summary: "Ruhige Feuerstelle am Waldrand, nicht offiziell ausgeschildert.",
    createdAt: "2026-08-31T17:42:00+02:00",
    location: { latitude: 47.25, longitude: 8.85, label: "Waldrand bei Rüti", source: "device" },
    attachments: [{ id: "att-grill-1", type: "image", name: "grillstelle.jpg" }],
    tags: ["Grillstelle", "Familie", "Ausflug", "Wald"],
    people: [],
    enrichment: { summary: "Persönlich entdeckter Grillplatz im Wald.", confidence: 0.93 },
  },
  {
    id: "restaurant-tipp",
    originalInput: "Marco empfiehlt dieses Restaurant im Tessin. Unbedingt das Risotto probieren.",
    inputType: "voice",
    title: "Restaurant-Tipp von Marco",
    summary: "Restaurantempfehlung fürs Tessin mit Fokus auf Risotto.",
    createdAt: "2026-08-30T20:10:00+02:00",
    location: { label: "Tessin", source: "extracted" },
    attachments: [],
    tags: ["Restaurant", "Tessin", "Essen"],
    people: ["Marco"],
    enrichment: { summary: "Persönliche Empfehlung eines Kollegen.", confidence: 0.88 },
  },
  {
    id: "produktfoto",
    originalInput: "Dieses Regal gefällt mir fürs Wohnzimmer.",
    inputType: "camera",
    title: "Regal fürs Wohnzimmer",
    summary: "Produktidee aus einem spontanen Foto.",
    createdAt: "2026-08-28T14:20:00+02:00",
    attachments: [{ id: "att-product-1", type: "image", name: "regal.jpg" }],
    tags: ["Produkt", "Wohnen"],
    people: [],
  },
  {
    id: "projektidee",
    originalInput: "Idee: kleine App, die Fundstücke aus Text, Sprache, Kamera oder Datei speichert und später wiederfindbar macht.",
    inputType: "text",
    title: "Persönliches Fundstück-Gedächtnis",
    summary: "Spontane Produktidee für eine KI-gestützte Erinnerungs-App.",
    createdAt: "2026-08-31T19:00:00+02:00",
    attachments: [],
    tags: ["Idee", "App", "KI"],
    people: [],
  },
];
