import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";
import { kipuFunctionTools, runKipuFunctionTool } from "@/lib/kipu-agent-tools";

const factSchema={type:"object",additionalProperties:false,properties:{label:{type:"string"},value:{type:"string"}},required:["label","value"]};
const memorySchema={type:"object",additionalProperties:false,properties:{title:{type:"string"},summary:{type:"string"},tags:{type:"array",items:{type:"string"},maxItems:3},people:{type:"array",items:{type:"string"},maxItems:8},category:{type:"string"},subject_location:{anyOf:[{type:"string"},{type:"null"}]},subject_location_is_from_user:{type:"boolean"},facts:{type:"array",items:factSchema,maxItems:5},representative_image_url:{anyOf:[{type:"string"},{type:"null"}]},representative_image_fit:{type:"string",enum:["cover","contain"]},image_reason:{type:"string"},related_idea_ids:{type:"array",items:{type:"string"},maxItems:5}},required:["title","summary","tags","people","category","subject_location","subject_location_is_from_user","facts","representative_image_url","representative_image_fit","image_reason","related_idea_ids"]};
type CaptureBody={text?:string;latitude?:number|null;longitude?:number|null};type Source={title?:string;url:string};type AgentResponse={id?:string;output_text?:string;output?:Array<Record<string,any>>};
function extractResponseText(payload:AgentResponse){if(typeof payload.output_text==="string"&&payload.output_text.trim())return payload.output_text;for(const output of payload.output??[])for(const content of output.content??[])if(typeof content?.text==="string"&&content.text.trim())return content.text;return null}
function extractSources(payload:AgentResponse){const sources:Source[]=[];for(const output of payload.output??[]){if(output.type!=="web_search_call")continue;for(const source of output.action?.sources??[])if(source?.url)sources.push({title:source.title,url:source.url})}return sources}
function cleanGeneratedText(value:string){return value.replace(/\[([^\]]+)\]\(https?:\/\/[^)]+\)/g,"$1").replace(/\((?:https?:\/\/[^)]+)\)/g,"").replace(/https?:\/\/\S+/g,"").replace(/\s{2,}/g," ").trim()}
async function callOpenAI(openAiKey:string,body:Record<string,unknown>){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok){const detail=await response.text();console.error("Kipu agent OpenAI error",response.status,detail);throw new Error(`openai_${response.status}`)}return(await response.json()) as AgentResponse}

async function runAgent(openAiKey:string,supabase:SupabaseClient,userId:string,text:string,latitude?:number|null,longitude?:number|null){
 const tools=[{type:"web_search"},...kipuFunctionTools];const allSources:Source[]=[];const hasCoords=Number.isFinite(latitude)&&Number.isFinite(longitude);
 const system=`Du bist Kipu, ein persönlicher Memory-Agent. Aus oft extrem knappem Input machst du die bestmögliche spätere Erinnerung. Du bist ein Agent: entscheide eigenständig, welche Tools du brauchst und in welcher Reihenfolge. Anwendungs-Code gibt dir Fähigkeiten, aber keine Kategorie-Regeln.

Deine Toolbox:
- Web Search: offene Recherche zu öffentlich identifizierbaren Dingen.
- search_images: generische Suche nach repräsentativen Bildkandidaten jeder Art. Nutze sie, wenn ein echtes Bild Wiedererkennung verbessert.
- inspect_web_page: konkrete relevante Seite genauer untersuchen.
- search_places: reale Orte/POIs identifizieren und Ortsdaten prüfen.
- reverse_geocode: GPS-Aufnahmekontext verstehen.
- search_my_ideas: bestehendes persönliches Gedächtnis durchsuchen.
- find_similar_ideas: mögliche Duplikate/Verbindungen zu bestehenden Erinnerungen finden.

Grundsätze:
- Keine Kategorie-Sonderlogik. Überlege aus Bedeutung und Kontext.
- Originalinput ist unveränderliche Wahrheit. Erfinde keine persönlichen Fakten.
- Recherchiere nur, wenn es die Erinnerung besser macht, aber bei konkret identifizierbaren Dingen darfst du proaktiv recherchieren.
- summary 1-2 kurze, natürliche Sätze. facts höchstens 5 wirklich nützliche Punkte. Keine URLs/Markdown/Quellenmarkup in summary oder facts.
- Für ein Bild: nutze search_images und/oder inspect_web_page. Wähle representative_image_url ausschließlich aus einer URL, die ein Tool tatsächlich geliefert hat. Prüfe, dass sie sehr wahrscheinlich die konkrete Entität zeigt. Wenn nichts Belastbares da ist: null.
- representative_image_fit cover für Szenen/Fotos, contain wenn das gesamte Motiv sichtbar bleiben soll.
- Maximal 3 gute Tags.
- Capture Location und Subject Location sind getrennt. GPS ist nie automatisch Subject Location.
- Wenn frühere Kipu-Ideen relevant sind, darfst du sie suchen und ihre IDs in related_idea_ids speichern. Nutze das auch sinnvoll zur Duplikaterkennung.
- Antworte am Ende ausschließlich im vorgegebenen strukturierten Schema.`;
 const userContext=hasCoords?`Persönlicher Input:\n${text}\n\nAufnahmekontext: GPS ${latitude}, ${longitude}. Dieser Ort ist NICHT automatisch der Ort des Fundstücks.`:`Persönlicher Input:\n${text}\n\nKein GPS-Aufnahmekontext verfügbar.`;
 let response=await callOpenAI(openAiKey,{model:"gpt-5.6-luna",tools,include:["web_search_call.action.sources"],input:[{role:"system",content:[{type:"input_text",text:system}]},{role:"user",content:[{type:"input_text",text:userContext}]}],text:{format:{type:"json_schema",name:"kipu_memory",strict:true,schema:memorySchema}}});
 for(let step=0;step<10;step++){
  allSources.push(...extractSources(response));const calls=(response.output??[]).filter((item)=>item.type==="function_call");if(!calls.length)break;const outputs=[];
  for(const call of calls){let args:Record<string,unknown>={};try{args=JSON.parse(call.arguments??"{}")}catch{}const result=await runKipuFunctionTool(call.name,args,{supabase,userId,openAiKey});outputs.push({type:"function_call_output",call_id:call.call_id,output:JSON.stringify(result)})}
  response=await callOpenAI(openAiKey,{model:"gpt-5.6-luna",previous_response_id:response.id,tools,include:["web_search_call.action.sources"],input:outputs,text:{format:{type:"json_schema",name:"kipu_memory",strict:true,schema:memorySchema}}});
 }
 allSources.push(...extractSources(response));const raw=extractResponseText(response);if(!raw)throw new Error("agent_no_final_output");const memory=JSON.parse(raw) as {title:string;summary:string;tags:string[];people:string[];category:string;subject_location:string|null;subject_location_is_from_user:boolean;facts:Array<{label:string;value:string}>;representative_image_url:string|null;representative_image_fit:"cover"|"contain";image_reason:string;related_idea_ids:string[]};memory.summary=cleanGeneratedText(memory.summary);memory.facts=memory.facts.map((f)=>({label:cleanGeneratedText(f.label),value:cleanGeneratedText(f.value)}));const uniqueSources:Source[]=[];const seen=new Set<string>();for(const source of allSources){if(!source.url||seen.has(source.url))continue;seen.add(source.url);uniqueSources.push(source)}return{memory,sources:uniqueSources.slice(0,10)};
}

export async function POST(request:Request){try{const body=(await request.json()) as CaptureBody;const text=body.text?.trim();if(!text)return NextResponse.json({error:"Text fehlt."},{status:400});if(text.length>5000)return NextResponse.json({error:"Text ist zu lang."},{status:400});const token=request.headers.get("authorization")?.replace(/^Bearer /,"");if(!token)return NextResponse.json({error:"Nicht angemeldet."},{status:401});const supabaseUrl=process.env.NEXT_PUBLIC_SUPABASE_URL,supabaseKey=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,openAiKey=process.env.OPENAI_API_KEY;if(!supabaseUrl||!supabaseKey||!openAiKey)return NextResponse.json({error:"Server-Konfiguration unvollständig."},{status:500});const supabase=createClient(supabaseUrl,supabaseKey,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const{data:userData,error:userError}=await supabase.auth.getUser(token);if(userError||!userData.user)return NextResponse.json({error:"Session ungültig."},{status:401});const{memory,sources}=await runAgent(openAiKey,supabase,userData.user.id,text,body.latitude,body.longitude);const hasCoords=Number.isFinite(body.latitude)&&Number.isFinite(body.longitude);const{data:idea,error:insertError}=await supabase.from("ideas").insert({user_id:userData.user.id,input_type:"text",original_input:text,title:memory.title,summary:memory.summary,tags:memory.tags,people:memory.people,latitude:hasCoords?body.latitude:null,longitude:hasCoords?body.longitude:null,location_label:memory.subject_location,location_source:memory.subject_location?(memory.subject_location_is_from_user?"extracted":"researched"):hasCoords?"device":null,enrichment:{category:memory.category,facts:memory.facts,sources,image_url:memory.representative_image_url,image_fit:memory.representative_image_fit,image_reason:memory.image_reason,related_idea_ids:memory.related_idea_ids,capture_location:hasCoords?{latitude:body.latitude,longitude:body.longitude}:null,agentic:true,toolbox_version:2,model:"gpt-5.6-luna",enriched_at:new Date().toISOString()}}).select("*").single();if(insertError){console.error("Supabase insert failed",insertError);return NextResponse.json({error:"Speichern in Supabase fehlgeschlagen.",detail:insertError.message},{status:500})}return NextResponse.json({idea});}catch(error){console.error("Kipu capture agent error",error);return NextResponse.json({error:"KI-Verarbeitung fehlgeschlagen."},{status:502})}}
