import { createClient } from "@supabase/supabase-js";
import { NextResponse } from "next/server";

const factSchema={type:"object",additionalProperties:false,properties:{label:{type:"string"},value:{type:"string"}},required:["label","value"]};
const ideaSchema={type:"object",additionalProperties:false,properties:{title:{type:"string"},summary:{type:"string"},tags:{type:"array",items:{type:"string"},maxItems:3},people:{type:"array",items:{type:"string"},maxItems:8},explicit_location:{anyOf:[{type:"string"},{type:"null"}]},location_mentioned:{type:"boolean"},location_is_subject:{type:"boolean"},category:{type:"string"},entity_type:{anyOf:[{type:"string"},{type:"null"}]},entity_name:{anyOf:[{type:"string"},{type:"null"}]},research_used:{type:"boolean"},research_summary:{anyOf:[{type:"string"},{type:"null"}]},facts:{type:"array",items:factSchema,maxItems:5},image_search_hint:{anyOf:[{type:"string"},{type:"null"}]}},required:["title","summary","tags","people","explicit_location","location_mentioned","location_is_subject","category","entity_type","entity_name","research_used","research_summary","facts","image_search_hint"]};
const imageChoiceSchema={type:"object",additionalProperties:false,properties:{selected_index:{anyOf:[{type:"integer"},{type:"null"}]},fit:{type:"string",enum:["cover","contain"]},reason:{type:"string"}},required:["selected_index","fit","reason"]};
type CaptureBody={text?:string;latitude?:number|null;longitude?:number|null};
type Source={title?:string;url:string};
type Candidate={url:string;sourceUrl:string;sourceTitle?:string};

function responseText(p:any){if(typeof p?.output_text==="string")return p.output_text;for(const o of p?.output??[])for(const c of o?.content??[])if(typeof c?.text==="string")return c.text;return null}
function extractSources(p:any){const out:Source[]=[];const seen=new Set<string>();for(const o of p?.output??[]){if(o?.type!=="web_search_call")continue;for(const s of o?.action?.sources??[]){if(!s?.url||seen.has(s.url))continue;seen.add(s.url);out.push({title:s.title,url:s.url})}}return out.slice(0,6)}
function absoluteUrl(value:string,base:string){try{return new URL(value,base).toString()}catch{return null}}
async function imageCandidates(sources:Source[]){const found:Candidate[]=[];const seen=new Set<string>();await Promise.all(sources.slice(0,5).map(async source=>{try{const r=await fetch(source.url,{headers:{"User-Agent":"Mozilla/5.0 KipuBot/1.0"},redirect:"follow",signal:AbortSignal.timeout(4500)});if(!r.ok)return;const html=(await r.text()).slice(0,500000);const patterns=[/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image(?::secure_url)?["']/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']twitter:image["']/i];for(const pattern of patterns){const match=html.match(pattern);if(!match?.[1])continue;const u=absoluteUrl(match[1].replace(/&amp;/g,"&"),source.url);if(u&&u.startsWith("http")&&!seen.has(u)){seen.add(u);found.push({url:u,sourceUrl:source.url,sourceTitle:source.title});break}}}catch{}}));return found.slice(0,6)}

async function chooseImage(openAiKey:string,idea:{title:string;entity_name:string|null;category:string;image_search_hint:string|null},candidates:Candidate[]){if(!candidates.length)return {url:null,fit:"cover",reason:"Keine Bildkandidaten gefunden."};const content:any[]=[{type:"input_text",text:`Wähle das Bild, das dieses gespeicherte Fundstück am besten repräsentiert.\nTitel: ${idea.title}\nEntität: ${idea.entity_name??"unbekannt"}\nKategorie: ${idea.category}\nBildabsicht: ${idea.image_search_hint??"repräsentatives Hauptbild"}\n\nRegeln: Wähle nur ein Bild, wenn es sehr wahrscheinlich die konkrete Entität zeigt. Für ein Buch wäre typischerweise das Cover passend, für ein Restaurant eine erkennbare Ansicht, für ein Produkt das konkrete Produkt, für einen Ort eine charakteristische Ansicht. Logo, generische Stockbilder, Navigationselemente oder thematisch nur ähnliche Bilder ablehnen. 'cover' bedeutet bildfüllend zuschneiden, 'contain' bedeutet vollständig zeigen.`}];candidates.forEach((c,i)=>{content.push({type:"input_text",text:`Kandidat ${i}: Quelle ${c.sourceTitle??c.sourceUrl}`});content.push({type:"input_image",image_url:c.url,detail:"low"})});try{const r=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",input:[{role:"user",content}],text:{format:{type:"json_schema",name:"kipu_image_choice",strict:true,schema:imageChoiceSchema}}})});if(!r.ok)return {url:null,fit:"cover",reason:"Bildauswahl fehlgeschlagen."};const raw=responseText(await r.json());if(!raw)return {url:null,fit:"cover",reason:"Keine Bildauswahl."};const choice=JSON.parse(raw);if(choice.selected_index===null||!candidates[choice.selected_index])return {url:null,fit:choice.fit,reason:choice.reason};return {url:candidates[choice.selected_index].url,fit:choice.fit,reason:choice.reason}}catch{return {url:null,fit:"cover",reason:"Bildauswahl fehlgeschlagen."}}
}

export async function POST(request:Request){try{const body=(await request.json()) as CaptureBody;const text=body.text?.trim();if(!text)return NextResponse.json({error:"Text fehlt."},{status:400});const token=request.headers.get("authorization")?.replace(/^Bearer /,"");if(!token)return NextResponse.json({error:"Nicht angemeldet."},{status:401});const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,openAiKey=process.env.OPENAI_API_KEY;if(!url||!key||!openAiKey)return NextResponse.json({error:"Server-Konfiguration unvollständig."},{status:500});const supabase=createClient(url,key,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}});const {data:userData,error:userError}=await supabase.auth.getUser(token);if(userError||!userData.user)return NextResponse.json({error:"Session ungültig."},{status:401});
const ai=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openAiKey}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.6-luna",tools:[{type:"web_search"}],include:["web_search_call.action.sources"],input:[{role:"system",content:[{type:"input_text",text:`Du bist Kipu, ein persönliches Fundstück-Gedächtnis. Aus minimalem Input machst du einen guten Gedächtnisanker. Recherchiere identifizierbare öffentliche Entitäten gezielt im Web. Maximal 3 hilfreiche Tags. research_summary 1-2 saubere Sätze ohne URLs. facts 2-5 nützliche Fakten. image_search_hint beschreibt kurz, welches visuelle Motiv die Erinnerung am besten repräsentieren würde, ohne eine URL zu erfinden (z.B. 'offizielles Cover des Buchs X', 'Außenansicht Restaurant Y', 'Produktfoto Modell Z', 'charakteristische Ansicht Ort Q'). GPS ist nur Aufnahmekontext. explicit_location nur aus dem Originalinput. location_is_subject nur true, wenn der Ort wirklich zum Fundstück gehört. Erfinde keine persönlichen Fakten oder Orte.`}]},{role:"user",content:[{type:"input_text",text:`Persönlicher Input:\n${text}`}]}],text:{format:{type:"json_schema",name:"kipu_idea",strict:true,schema:ideaSchema}}})});if(!ai.ok){console.error("OpenAI",ai.status,await ai.text());return NextResponse.json({error:"KI-Verarbeitung fehlgeschlagen."},{status:502})}const payload=await ai.json();const raw=responseText(payload);if(!raw)return NextResponse.json({error:"KI-Antwort war leer."},{status:502});const s=JSON.parse(raw);const webSources=extractSources(payload);const candidates=await imageCandidates(webSources);const chosen=await chooseImage(openAiKey,s,candidates);const hasCoords=Number.isFinite(body.latitude)&&Number.isFinite(body.longitude);const subjectLocation=s.location_mentioned&&s.location_is_subject?s.explicit_location:null;
const {data:idea,error:insertError}=await supabase.from("ideas").insert({user_id:userData.user.id,input_type:"text",original_input:text,title:s.title,summary:s.summary,tags:s.tags,people:s.people,latitude:hasCoords?body.latitude:null,longitude:hasCoords?body.longitude:null,location_label:subjectLocation,location_source:subjectLocation?"extracted":hasCoords?"device":null,enrichment:{category:s.category,entity_type:s.entity_type,entity_name:s.entity_name,research_used:s.research_used,research_summary:s.research_summary,facts:s.facts,sources:webSources,image_url:chosen.url,image_fit:chosen.fit,image_reason:chosen.reason,image_search_hint:s.image_search_hint,image_candidates:candidates,capture_location:hasCoords?{latitude:body.latitude,longitude:body.longitude}:null,model:"gpt-5.6-luna",enriched_at:new Date().toISOString()}}).select("*").single();if(insertError){console.error(insertError);return NextResponse.json({error:"Speichern in Supabase fehlgeschlagen.",detail:insertError.message},{status:500})}return NextResponse.json({idea});}catch(e){console.error(e);return NextResponse.json({error:"Unerwarteter Fehler."},{status:500})}}
